### ISSUE TITLE
"Signature check for DIGESTS failed." after fresh install

### ISSUE THREAD

**Issue by internetionals** [woofwoofinc/rktmachine#43]
After freshly installing RktMachine 1.0.0 and running it for the first time, I get:

    $ /Applications/RktMachine.app/Contents/Resources/commands/start_vm.command ; exit;
    
    
    
     
     
    
    
         ______ __    __   _______            __    __
        |   __ |  |--|  |_|   |   .---.-.----|  |--|__.-----.-----.
        |      |    <|   _|       |  _  |  __|     |  |     |  -__|
        |___|__|__|__|____|__|_|__|___._|____|__|__|__|__|__|_____|
    
                                                    Woof Woof, Inc.
    
    > booting rktmachine (1/1)
    [WARN] /Users/justin/.coreos/images/stable/1520.6.0/coreos_production_pxe.vmlinuz missing -  stable/1520.6.0 ignored
    ---> downloading and verifying stable/1520.6.0
    [ERROR] Signature check for DIGESTS failed.
     
    Press [Enter] to continue.

**Comment by daithiocrualaoich** [comment]
Hi @internetionals, thanks for reporting this.

The CoreOS signing key was updated in https://coreos.com/releases/#1465.7.0 and the bundled corectl which handles the download doesn’t include the updated key. For now I’ll pin the CoreOS version to the known good 1465.6.0 CoreOS stable release and create a 1.0.1 release here for you.

There’s an upstream fix in corectl which incorporates the new signing key but the latest code isn’t building so well for me. I’ll repackage and release with the latest corectl when I get it working.

Delete ~/.coreos and ~/.rktmachine if you still have problems with the new version.

Thanks again for raising this. It’s really appreciated.

**Comment by internetionals** [comment]
Hi @daithiocrualaoich,

Thanks for the quick response. I immediately tried the new version on my laptop and now all seems to work as expected.
